### ISSUE TITLE
Backend-Two-Week-RoadMap-[Dehghani & Jalali]

### ISSUE THREAD

**Issue by MohammadHDehghani** [Star-Academy/codestar-intern-issues#737]
##Basics
- [x] [Read Health and Git Part of Intro documents](https://star-academy.github.io/codestar-documents/docs/intro)

##[Phase 1](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase01-simple-project)

-   [ ] Introduction
-   [ ] Definition
    -   [ ] Data Extraction
    -   [ ] Data Transformation
    -   [ ] Data Loading
-   [ ] Learning
    -   [ ] Register
    -   [ ] Datasets
    -   [ ] Pipelines
    -   [ ] Add Source
    -   [ ] Add Destination
    -   [ ] Processors
    -   [ ] Filters
    -   [ ] Run Pipeline
    -   [ ] Cleansing
    -   [ ] Aggregation
    -   [ ] Join
    -   [ ] Export
    -   [ ] Share

##[Phase 2](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase02-clean-code)

-   [x] Clean Code Importance

    -   [x] Think about the questions and discuss your answers with your teammate
        -   [x] Write your answers to question 1:
            1. `ایجاد کردن یک برنامه تقریبا آسان‌ترین کار برای یک مهندس نرم‌افزار است. چالش اصلی یک مهندس نرم‌افزار، توسعه‌ی همان برنامه در آینده است؛ بنابراین، به‌گونه‌ای کدهای خود را بنویسیم و معماری خود را انتخاب کنیم که توسعه‌ی آن در آینده با کم‌ترین چالش ممکن روبه‌رو باشد.`
            1. `اکثر وقت برنامه‌نویسان به‌جای نوشتن کد جدید صرف خواندن کدهای نوشته‌شده می‌شود؛ در نتیجه لازم است تا کدها را به‌گونه‌ای بنویسیم که خواندن و درک آن‌ها در ‌کم‌ترین زمان ممکن قادر باشد.`
            1. `نوشتن کد کثیف و غیر بهینه شاید در ابتدا به‌ظاهر در زمان ما صرفه‌جویی کند، اما در آینده می‌تواند مشکلاتی را به‌وجود بیاورد که نه تنها زمان زیادی از ما میگیرد، بلکه حتی ممکن است هزینه‌های اضافه‌ای بر روی دست شرکت بگذارد؛ به‌طور مثال ممکن است شرکت مجبور باشد برای رفع این مشکلات مجبور به خرید سرورهای بیش‌تر یا سخت‌افزار‌های گران‌تر شود.`
        -   [x] Write your answers to question 2:
            1. `در بسیاری از پروژه‌ها، ابتدا یک تیم روی آن پروژه کار می‌کند و در آینده ممکن است تیم دیگری مسئولیت آن پروژه را به عهده بگیرد. اگر تیم اول کدهای غیر بهینه‌ای به تیم دوم تحویل بدهند، این کار باعث می‌شود تا هزینه‌های مالی و زمانی زیادی به شرکت و تیم دوم تحمیل شود که همه‌ی این‌ها از کد غیر بهینه‌ نشأت می‌گیرند.`
            1. `این روز‌ها اکثر شرکت‌ها بیش‌تر از ۸۰ درصد منابع خود را برای تعمیر و نگهداری کد‌های خود مصرف می‌کنند. اما اگر توسعه‌دهندگان در همان ابتدای کار تلاش خود را بکنند تا کدهای بهینه‌تر و تمیز‌تری بنویسند، این اعدام و ارقام تا حد زیادی کاهش پیدا می‌کنند و به وضعیت کلی شرکت کمک می‌کند.`
            1. `از آن‌جایی که در مقیاس صنعتی، اتفاقاتی از قبیل تغییر محیط اجرایی پروژه یا نیازمندی‌های پروژه بیش‌تر رخ می‌دهند، تأثیر داشتن کدهای تمیز و معماری مناسب، بیشتر به چشم می‌آید.`
    -   [x] Visit the mentioned links in the doc and read the article individually
    -   [ ] Think about the questions and discuss your answers with your teammate
        -   [ ] Write your answers to question 1:
            1. `[ANSWER 01]`
            1. `[ANSWER 02]`
            1. `[ANSWER 03]`
        -   [ ] Write your answers to question 2:
            1. `[ANSWER 01]`
            1. `[ANSWER 02]`
            1. `[ANSWER 03]`

-   [x] Read about these famous code smells individually

    -   [x] Long Method
    -   [x] Primitive Obsession
    -   [x] Large Class
    -   [x] Long Parameter List
    -   [x] Temporary Field
    -   [x] Duplicate Code

    Which code smells of above list exist in your search project?

    `Duplicate Code`

-   [x] Read about SOLID principles in software engineering:

    -   [x] Single Responsibility
    -   [x] Open-Close
    -   [x] Liskov Substitution
    -   [x] Interface Segregation
    -   [x] Dependency Inversion

-   [x] Refactoring Techniques:

    -   [x] Take a look at Refactoring Techniques
    -   [x] Fix code smells you mentioned for your search project in a new branch
    -   [x] Make a PR (Pull Request) from new branch to master but do not merge it

        `https://github.com/Star-Academy/Fall1402-TwoWeek-InternShip-Backend/pull/2`

-   [x] Code Review:
    -   [x] Read Review Guides
       
##[Phase 3](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase03-c-sharp)

-   [x] Install **Requirements**:

    -   [x] Install **.NET SDK**
    -   [x] Install VS Code **C# Extension**

-   [x] Read about **Solution** and **Project** in C# environment

-   [x] Write your first Hello World C# app

-   [x] Read about **NuGet** and learn how to use it

    -   [x] Install **System.Text.Json** and serialize an object

-   [x] Advanced Knowledge:

    -   [x] Follow mentioned tutorial and learn about Reading data from **Console**
    -   [x] Read about **Naming Guidelines** in C#
    -   [x] Install **.Net Interactive**
        -   [x] Execute first code
        -   [x] Execute second code
    -   [x] Read about **Lambda Expressions**
    -   [x] Read about **Extension Method**
    -   [x] Read about **LINQ**

-   [x] Implement Student Grades & Average Project in C#

##[Phase 4](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase04-unit-test)

-   [x] Read about **Unit Test** and its importance

    -   [x] Find out what's Unit Testing
    -   [x] Write three reasons of using Unit Testing in Software development:
        1. `صرفه‌جویی در وقت و هزینه در درازمدت`
        1. `پیداکردن آسان‌تر باگ‌ها یا قسمت‌هایی از کد که می‌توانند در آینده مشکل ساز شوند`
        1. `اطمینان بیشتر از صحت عملکرد برنامه نوشته شده`

-   [x] Read about **Code Coverage** and its importance in Unit Testing

-   [x] Unit Testing in **C#**:

    -   [x] Find out how to write unit tests in C# with **xUnit**
    -   [x] Find out how to run unit tests and check code coverage

-   [x] Read about the effect of SOLID principles on Unit Testing

    -   [x] Write your findings briefly:
        -   `همانقدر که رعایت اصول سالید در پیاده‌سازی و توسعه نرم‌افزار نقش حیاتی دارد. رعایت این اصول در مرحله تست نویسی هم به ما کمک می‌کند. به این صورت که هرقدر این اصول را بهتر رعایت کرده باشیم در طراحی و نوشتن تست‌ها با مشکلات کمتری روبه‌رو می‌شویم. و از سوی دیگر می‌توان این‌گونه هم گفت که سهولت در تست نویسی نیز معیاری برای فهمیدن این مسئله است که چقدر اصول سالید درست رعایت شده‌اند.`

-   [x] **Mocking** technique:

    -   [x] Find out what's Mocking
    -   [x] Find out why we should use mocking in unit tests
    -   [x] Find out how to use mocking in C#

-   [x] Writing unit tests for simple calculator
    -   [x] Clone Project from [here](https://github.com/Star-Academy/SimpleCalculator)
    -   [x] Copy project to your own Repository
    -   [x] Start writing tests
    -   [x] Increase code coverage (line or statement coverage) to at least 95%:
            `100% line coverage and 95% block coverage.`

##[Phase 5](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase05-tdd)

-   [x] Read about **TDD** concepts

    -   [x] Write the steps of TDD cycle:
        1. نوشتن تستی که نتیجه‌اش fail باشد.
        2.  نوشتن کدی که باعث pass شدن تست نوشته شده شود.
        3. refactor کردن کد زده شده در مرحله شماره 2.

-   [x] Effects of applying **SOLID** principles in **TDD**

    -   [x] Think about that in your team, then write you answer:
        1. `رعایت کردن اصول SOLID در رویکرد TDD به ما کمک خواهد کرد تا منظم تر فکر کنیم، تست بنویسیم و در نهایت هم کد تمیزتر و استانداردتری خواهیم داشت.`
    -   [x] Read about above title then update your answer:
        1. `با اینکه رویکرد TDD ما را مجبور به استفاده از اصول SOLID نمی‌کند اما بسیار پیشنهاد می‌شود تا در این رویکرد از این اصول استفاده شود زیرا کار برای ما بسیار آسان‌تر و سریع تر خواهد شد و ما را از بسیاری از مشکلات و سختی‌های احتمالی نجات خواهد داد.`

-   [x] Reimplement Search Project in `C#` with **TDD** approach
    -   [x] Write tests
    -   [x] Implement the Search project so that all tests are passed
    -   [x] Run tests and debug if some tests fail
    -   [x] Refactor your code

##[Phase 6](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase07-SQL)

- [x] Read the introduction to SQL
- [x] Understand basic concepts
- [x] Install required softwares
    - [x] Download PostgreSQL
    - [x] Download Azure Data Studio
    - [x] Install PostgreSQL with default configs
    - [x] Install ADS
    - [x] Run and configure ADS to work with Postgres
    - [x] Create connection to the Postgres instance
- [x] Create your own database
- [x] Get familiar with different data types in Postgres
    - [x] Write a suitable data type for each of the fields below:
        - `interval` for flight time
        - `varchar` for email address
        - `bool` for a boolean variable
        - `float` for stature
- [x] Store some data
    - [x] Create a table with arbitrary columns with data types you learned in the previous section
    - [x] Insert some sample data into your table
    - [x] Retrieve your data with different `SELECT` statements and different conditions
    - [x] Try to change at least one of your table columns attributes using `ALTER` statement
- [x] Perceive the importance and usage of each key
    - [x] Add primary key constraint to your table
    - [x] Try inserting different values for primary key and check whether it produces error or not
        - Try inserting duplicate primary key. Error [duplicate key value violates unique constraint "student_grade_pkey" ]
        - Try inserting `NULL` primary key. Error [null value in column "id" of relation "student_grade" violates not-null constraint ]
    - [x] Create a new table which is related to your existing table with a foreign key
    - [x] Try inserting different values for foreign key to produce different errors
        - Try inserting none existing foreign key. Error [insert or update on table "student_information" violates foreign key constraint "fk" ]
        - Try inserting duplicate foreign key. Error [No Error ]
        - Try inserting `NULL` foreign key. Error [No Error ]
- [x] Perceive different types of joins
    - [x] Write the corresponding set operation for each join like the given example
        - A Inner Join B : A ∩ B
        - A Left Outer Join B : `A`
        - A Right Outer Join B : `B`
        - A Full Outer Join B : `A U B`
    - [x] Test different joins on you tables
- [x] Work with functions
    - [x] Write a query for each present function in the document
     
##[Phase 7](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase08-EFCore)

- [x] Implement Top 3 Student project with EfCore in C#

##[Phase 8](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase09-web)

## Web history

- [x] Before starting: Read the link about history and purpose of creating & developing Web, then answer this questions:
  - [x] How did developers provide server-client softwares for users before creation of web technologies?
  
      `برنامه‌‌ها دارای نسخه‌های کلاینتی بودند که به اجبار باید روی هر کامپیوتر کلاینت نصب می‌شدند.`

  - [x] What was the main trouble with traditional technologies before web?
  
      `هر برنامه باید برای سیستم عامل های متعددی طراحی می‌شد تا تمام کاربران صرف نظر از سیستم عامل خود بتوانند از آن استفاده کنند.`

  - [x] How did web overcome this main trouble?
  
      `برنامه‌ها به جای اینکه به سیستم‌عامل‌ها متکی باشند از اینجا به بعد به مرورگرها وابسته بودند و اینگونه مشکل برطرف شد.`

## ASP.NET Core

- [x] Getting Started with HTTP:
  - [x] What does a protocol mean?
  
    `پروتکل سیستمی است که مشخص می‌کند اطلاعات بین دو یا چند سیستم چگونه جابه‌جا شود.`

  - [x] Why designing a protocol for communication is important prerequirement of all other web related technologies?
  
    `فلسفه تکنولوژی‌های مبتنی بر وب برقراری ارتباط بین اجزای مختلف وب است. در نتیجه داشتن یک پروتکل استاندارد و واحد که نحوه برقراری این ارتباط را مشخص کند از اهمیت بالایی برخوردار است.`

  - [x] Try to get familier with HTTP by reading links.
  - [x] Why HTTP is most popular protocol in web technologies?

    `چون یک پروتکل ساده است، علاوه بر فرمت HTML از فرمت‌های دیگر مانند فایل‌های تصویری و صوتی هم پشتیبانی می‌کند، توسعه در بستر آن آسان است  و مستقل از پلتفرم نیز می‌باشد.`

  - [x] What is the most interesting aspect of HTTP in your opinion?
  
    `سینتکس آن بسیار ساده و قابل درک است و قابلیت توسعه بالایی نیز دارد.`

- [x] Getting Started with REST:
  - [x] Read mentioned links.
  - [x] Why do we need RESTful APIs?
  
    `معماری ساده و کارآمدی برای نوشتن APl هاست که از ورژن بندی پشتیبانی می‌کند و با استفاده از آن می‌توانیم رابط های خوبی بر حسب نیاز ایجاد کنیم.`

- [x] Getting Started with Asp.net Core:
  - [x] Read mentioned links.
  - [x] Create a hello world API.
  - [x] Call your api from browser.
  - [x] Play with routing options! (Try to use it & enjoy it!)
  - [x] Why do we need configurable routings in web development?
  
    `بر حسب پروژه‌ای که مشغول کار بر روی آن هستیم. ممکن است نیاز داشته باشیم تا مسیرها را به صورت دستی نیز عوض کنیم تا به هماهنگی بهتری برسیم و بتوانیم از روی هر مسیر بفهمیم که مرتبط با کدام اکشن متود می‌باشد.`
  
  - [x] Play with dependency injection! (Define an interface & inject interface implementation to code)
  - [ ] Why do we need dependency injection?
  
    `[FILL HERE WITH YOUR ANSWER. (feel free to write in persian)]`
  - [x] Play with parameter binding! (use different modes)
  - [x] Install postman.
  - [x] Call your APIs with postman.
  
- [x] Implement Asp.net Core Project:
  - [x] Design your search API.
  - [x] Implement & Test your API.
