### ISSUE TITLE
Frontend-Two-Week-RoadMap-Rahmani-Samani-Jafari-Farahani

### ISSUE THREAD

**Issue by alirrah** [Star-Academy/codestar-intern-issues#738]
##Basics
- [x] [Read Health and Git Part of Intro documents](https://star-academy.github.io/codestar-documents/docs/intro)

## HTML
- [x] [Semantic HTML](https://web.dev/learn/html/semantic-html)
- [x] [Headings and sections](https://web.dev/learn/html/headings-and-sections)
- [x] [Attributes](https://web.dev/learn/html/attributes)
- [x] [Lists](https://web.dev/learn/html/lists)
- [x] [Tables](https://web.dev/learn/html/tables)
- [x] [Forms](https://web.dev/learn/html/forms)
- [x] [HTML APIs](https://web.dev/learn/html/apis)
- [x] [Template, slot, and shadow](https://web.dev/learn/html/template)

## CSS
- [x] [Selectors](https://web.dev/learn/css/selectors)
- [x] [The cascade](https://web.dev/learn/css/the-cascade)
- [x] [Specificity](https://web.dev/learn/css/specificity)
- [x] [Inheritance](https://web.dev/learn/css/inheritance)
- [x] [Layout](https://web.dev/learn/css/layout)
- [x] [Flexbox](https://web.dev/learn/css/flexbox)
- [x] [Grid](https://web.dev/learn/css/grid)
- [x] [Pseudo-elements](https://web.dev/learn/css/pseudo-elements)
- [x] [Pseudo-classes](https://web.dev/learn/css/pseudo-classes)
- [x] [Functions](https://web.dev/learn/css/functions)
- [x] [Overflow](https://web.dev/learn/css/overflow)
## Exercise 1 (landing page)
- [x] Implement a landing page for a game store website using only html and css.
- [x] Make a pr (pull request) in github.
- [x] Get your pr approved by 2 person.
## JS
- [x] [Classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)
- [x] [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
- [x] [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
- [x] [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)
- [x] [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
- [x] [apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)
- [x] [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
- [x] [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
- [x] [DevTools](https://developer.chrome.com/docs/devtools/overview/)

## TypeScript
- [x] [TypeScript for JavaScript Programmers](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)
- [x] [Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
- [x] [Type Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html#handbook-content)
- [x] [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html#hello-world-of-generics)
- [x] [Utility Types](https://www.typescriptlang.org/docs/handbook/utility-types.html)
- [x] [Narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html)

## Angular
- [x] [Component](https://angular.dev/guide/components)
- [x] [Directives](https://angular.dev/guide/directives)
- [ ] [Dependency injection](https://angular.dev/guide/di)
- [x] [Routing](https://angular.dev/guide/routing)
- [ ] [Pipes](https://angular.dev/guide/pipes)
- [ ] [HTTP client](https://angular.dev/guide/http)
- [ ] [Testing](https://angular.dev/guide/testing)
- [ ] [DevTools(Angular)](https://angular.dev/tools/devtools)

##Frontend references 
- [Best Practices](https://roadmap.sh/best-practices/frontend-performance)

 - https://www.youtube.com/@ChromeDevs
 - https://www.youtube.com/@DecodedFrontend
 - https://www.youtube.com/@WebDev
- https://www.aparat.com/Code_star/Code_star
- https://github.com/Star-Academy/codestar-documents/tree/master/docs/frontend
