### ISSUE TITLE
Frontend-Two-Week-RoadMap-Ebrahimi

### ISSUE THREAD

**Issue by AliSK81** [Star-Academy/codestar-intern-issues#740]
##Basics
- [x] [Read Health and Git Part of Intro documents](https://star-academy.github.io/codestar-documents/docs/intro)

## HTML
- [x] [Semantic HTML](https://web.dev/learn/html/semantic-html)
- [x] [Headings and sections](https://web.dev/learn/html/headings-and-sections)
- [x] [Attributes](https://web.dev/learn/html/attributes)
- [x] [Lists](https://web.dev/learn/html/lists)
- [x] [Tables](https://web.dev/learn/html/tables)
- [x] [Forms](https://web.dev/learn/html/forms)
- [x] [HTML APIs](https://web.dev/learn/html/apis)
- [x] [Template, slot, and shadow](https://web.dev/learn/html/template)

## CSS
- [x] [Selectors](https://web.dev/learn/css/selectors)
- [ ] [The cascade](https://web.dev/learn/css/the-cascade)
- [ ] [Specificity](https://web.dev/learn/css/specificity)
- [ ] [Inheritance](https://web.dev/learn/css/inheritance)
- [ ] [Layout](https://web.dev/learn/css/layout)
- [ ] [Flexbox](https://web.dev/learn/css/flexbox)
- [ ] [Grid](https://web.dev/learn/css/grid)
- [ ] [Pseudo-elements](https://web.dev/learn/css/pseudo-elements)
- [ ] [Pseudo-classes](https://web.dev/learn/css/pseudo-classes)
- [ ] [Functions](https://web.dev/learn/css/functions)
- [ ] [Overflow](https://web.dev/learn/css/overflow)

## Exercise 1 (landing page)
- [ ] Implement a landing page for a game store website using only html and css.
- [ ] Make a pr (pull request) in github.
- [ ] Get your pr approved by 2 person.
## JS
- [ ] [Classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)
- [ ] [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
- [ ] [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
- [ ] [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)
- [ ] [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
- [ ] [apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)
- [ ] [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
- [ ] [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
- [ ] [DevTools](https://developer.chrome.com/docs/devtools/overview/)

## TypeScript
- [ ] [TypeScript for JavaScript Programmers](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)
- [ ] [Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
- [ ] [Type Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html#handbook-content)
- [ ] [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html#hello-world-of-generics)
- [ ] [Utility Types](https://www.typescriptlang.org/docs/handbook/utility-types.html)
- [ ] [Narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html)

## Angular
- [ ] [Component](https://angular.dev/guide/components)
- [ ] [Directives](https://angular.dev/guide/directives)
- [ ] [Dependency injection](https://angular.dev/guide/di)
- [ ] [Routing](https://angular.dev/guide/routing)
- [ ] [Pipes](https://angular.dev/guide/pipes)
- [ ] [HTTP client](https://angular.dev/guide/http)
- [ ] [Testing](https://angular.dev/guide/testing)
- [ ] [DevTools(Angular)](https://angular.dev/tools/devtools)

## Frontend references 
- [Best Practices](https://roadmap.sh/best-practices/frontend-performance)

 - https://www.youtube.com/@ChromeDevs
 - https://www.youtube.com/@DecodedFrontend
 - https://www.youtube.com/@WebDev
- https://www.aparat.com/Code_star/Code_star
- https://github.com/Star-Academy/codestar-documents/tree/master/docs/frontend
