### ISSUE TITLE
Frontend-Two-Week-RoadMap-Khodaei

### ISSUE THREAD

**Issue by At1X** [Star-Academy/codestar-intern-issues#741]
##Basics
- [X] [Read Health and Git Part of Intro documents](https://star-academy.github.io/codestar-documents/docs/intro)

## HTML
- [X] [Semantic HTML](https://web.dev/learn/html/semantic-html)
- [X] [Headings and sections](https://web.dev/learn/html/headings-and-sections)
- [X] [Attributes](https://web.dev/learn/html/attributes)
- [X] [Lists](https://web.dev/learn/html/lists)
- [X] [Tables](https://web.dev/learn/html/tables)
- [X] [Forms](https://web.dev/learn/html/forms)
- [X] [HTML APIs](https://web.dev/learn/html/apis)
- [X] [Template, slot, and shadow](https://web.dev/learn/html/template)

## CSS
- [X] [Selectors](https://web.dev/learn/css/selectors)
- [X] [The cascade](https://web.dev/learn/css/the-cascade)
- [X] [Specificity](https://web.dev/learn/css/specificity)
- [X] [Inheritance](https://web.dev/learn/css/inheritance)
- [X] [Layout](https://web.dev/learn/css/layout)
- [X] [Flexbox](https://web.dev/learn/css/flexbox)
- [X] [Grid](https://web.dev/learn/css/grid)
- [X] [Pseudo-elements](https://web.dev/learn/css/pseudo-elements)
- [X] [Pseudo-classes](https://web.dev/learn/css/pseudo-classes)
- [X] [Functions](https://web.dev/learn/css/functions)
- [X] [Overflow](https://web.dev/learn/css/overflow)

## Exercise 1 (landing page)
- [X] Implement a landing page for a game store website using only html and css.
- [X] Make a pr (pull request) in github.
- [ ] Get your pr approved by 2 person.
## JS
- [X] [Classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)
- [X] [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
- [X] [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set)
- [X] [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)
- [X] [bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)
- [X] [apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)
- [X] [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
- [X] [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)
- [X] [DevTools](https://developer.chrome.com/docs/devtools/overview/)

## TypeScript
- [X] [TypeScript for JavaScript Programmers](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html)
- [X] [Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
- [X] [Type Inference](https://www.typescriptlang.org/docs/handbook/type-inference.html#handbook-content)
- [X] [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html#hello-world-of-generics)
- [X] [Utility Types](https://www.typescriptlang.org/docs/handbook/utility-types.html)
- [X] [Narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html)

## Angular
- [X] [Component](https://angular.dev/guide/components)
- [X] [Directives](https://angular.dev/guide/directives)
- [X] [Dependency injection](https://angular.dev/guide/di)
- [X] [Routing](https://angular.dev/guide/routing)
- [X] [Pipes](https://angular.dev/guide/pipes)
- [X] [HTTP client](https://angular.dev/guide/http)
- [X] [Testing](https://angular.dev/guide/testing)
- [X] [DevTools(Angular)](https://angular.dev/tools/devtools)

## Frontend references 
- [Best Practices](https://roadmap.sh/best-practices/frontend-performance)

 - https://www.youtube.com/@ChromeDevs
 - https://www.youtube.com/@DecodedFrontend
 - https://www.youtube.com/@WebDev
- https://www.aparat.com/Code_star/Code_star
- https://github.com/Star-Academy/codestar-documents/tree/master/docs/frontend
