### ISSUE TITLE
Backend-Two-Week-RoadMap-(Samimi-Khorasanizadeh)

### ISSUE THREAD

**Issue by RAAvenger** [Star-Academy/codestar-intern-issues#743]
## Basics
- [x] [Read Health and Git Part of Intro documents](https://star-academy.github.io/codestar-documents/docs/intro)

## [Phase 1](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase01-simple-project)

-   [x] Basic Knowledge
    -   [x] Think individually about the questions before starting
    -   [x] Read individually about Inverted Index
-   [x] Read about Pair Programming.
-   [x] Practice 1
    -   [x] Implement a simple Inverted Index with Java (Pair Programming)
    -   [x] Implement a `FileReader` class which reads all files in a folder; each file is a document in your Inverted Index
    -   [x] Implement an `InvertedIndex` class which contains all tokens and the list of related documents per each token
    -   [x] Test your program with sample dataset mentioned in the doc
-   [x] Practice 2
    -   [x] Add support for words that start with + (or feature)
    -   [x] Add support for words that start with nothing (and feature)
    -   [x] Add support for words that start with - (exclude feature)

## [Phase 2](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase02-clean-code)

-   [x] Clean Code Importance

    -   [x] Think about the questions and discuss your answers with your teammate
        -   [x] Write your answers to question 1:
            1. توسعه پذیری کد
            2. افزایش خوانایی
            3. افزایش سرعت توسعه
            4. کاهش فرسایش روانی
        -   [x] Write your answers to question 2:
            1. بالا بودن پیچیدگی
            2. بالا بودن سطح اهمیت
            3. توسعه طولانی مدت کد
    -   [x] Visit the mentioned links in the doc and read the article individually
    
-   [x] Read about these famous code smells individually

    -   [x] Long Method
    -   [x] Primitive Obsession
    -   [x] Large Class
    -   [x] Long Parameter List
    -   [x] Temporary Field
    -   [x] Duplicate Code

    Which code smells of above list exist in your search project?

    Primitive Obsession

-   [x] Read about SOLID principles in software engineering:

    -   [x] Single Responsibility
    -   [x] Open-Close
    -   [x] Liskov Substitution
    -   [x] Interface Segregation
    -   [x] Dependency Inversion

-   [x] Refactoring Techniques:

    -   [x] Take a look at Refactoring Techniques
    -   [x] Fix code smells you mentioned for your search project in a new branch
    -   [x] Make a PR (Pull Request) from new branch to master but do not merge it

        کد اسمل‌ها در زمان کدنویسی در برنچ فاز یک فیکس شدند.

-   [x] Code Review:
    -   [x] Read Review Guides
       
## [Phase 3](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase03-c-sharp)

-   [x] Install **Requirements**:

    -   [x] Install **.NET SDK**
    -   [x] Install VS Code **C# Extension**

-   [x] Read about **Solution** and **Project** in C# environment

-   [x] Write your first Hello World C# app

-   [x] Read about **NuGet** and learn how to use it

    -   [x] Install **System.Text.Json** and serialize an object

-   [x] Advanced Knowledge:

    -   [x] Follow mentioned tutorial and learn about Reading data from **Console**
    -   [x] Read about **Naming Guidelines** in C#
    -   [x] Install **.Net Interactive**
        -   [x] Execute first code
        -   [x] Execute second code
    -   [x] Read about **Lambda Expressions**
    -   [x] Read about **Extension Method**
    -   [x] Read about **LINQ**

-   [x] Implement Student Grades & Average Project in C#

## [Phase 4](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase04-unit-test)

-   [x] Read about **Unit Test** and its importance

    -   [x] Find out what's Unit Testing
    -   [x] Write three reasons of using Unit Testing in Software development:
        1. مشخص شدن باگ‌ها در زمان توسعه
        2. اطمینان از کارکرد صحیح کد پس از تغییر
        3. ساختارمند شدن کد
        4. داکیومنت کردن کد به شکل کد 

-   [x] Read about **Code Coverage** and its importance in Unit Testing

-   [x] Unit Testing in **C#**:

    -   [x] Find out how to write unit tests in C# with **xUnit**
    -   [x] Find out how to run unit tests and check code coverage

-   [x] Read about the effect of SOLID principles on Unit Testing

    -   [x] Write your findings briefly:
        -  توجه به سالید باعث می‌شود که هر کلاس در کد یک مسئولیت مشخص داشته باشد و تست کردن کلاس‌های با مسئولیت مشخص ساده‌تر است.

-   [x] **Mocking** technique:

    -   [x] Find out what's Mocking
    -   [x] Find out why we should use mocking in unit tests
    -   [x] Find out how to use mocking in C#

-   [x] Writing unit tests for simple calculator
    -   [x] Clone Project from [here](https://github.com/Star-Academy/SimpleCalculator)
    -   [x] Copy project to your own Repository
    -   [x] Start writing tests
    -   [x] Increase code coverage (line or statement coverage) to at least 95%:
            100%

## [Phase 5](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase05-tdd)

-   [x] Read about **TDD** concepts

    -   [x] Write the steps of TDD cycle:
        1. Red
        2. Green
        3. Refactor

-   [x] Effects of applying **SOLID** principles in **TDD**

    -   [x] Think about that in your team, then write you answer:
        1. با توجه به اینکه برای هر یونیت کد به صورت جدا تست نوشته شده، باید برای ایجاد ساختار متناسب با تست، به صورت سالید کد بزنیم.
    -   [x] Read about above title then update your answer.

-   [x] Reimplement Search Project in `C#` with **TDD** approach
    -   [x] Write tests
    -   [x] Implement the Search project so that all tests are passed
    -   [x] Run tests and debug if some tests fail
    -   [x] Refactor your code

## [Phase 6](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase07-SQL)

- [x] Read the introduction to SQL
- [x] Understand basic concepts
- [x] Install required softwares
    - [x] Download PostgreSQL
    - [x] Download Azure Data Studio
    - [x] Install PostgreSQL with default configs
    - [x] Install ADS
    - [x] Run and configure ADS to work with Postgres
    - [x] Create connection to the Postgres instance
- [x] Create your own database
- [x] Get familiar with different data types in Postgres
    - [x] Write a suitable data type for each of the fields below:
        - `DATE TIME` for flight time
        - `VARCHAR` for email address
        - `BOOL` for a boolean variable
        - `INT` for stature
- [x] Store some data
    - [x] Create a table with arbitrary columns with data types you learned in the previous section
    - [x] Insert some sample data into your table
    - [x] Retrieve your data with different `SELECT` statements and different conditions
    - [x] Try to change at least one of your table columns attributes using `ALTER` statement
- [x] Perceive the importance and usage of each key
    - [x] Add primary key constraint to your table
    - [x] Try inserting different values for primary key and check whether it produces error or not
        - Try inserting duplicate primary key. Error [ ]
        - Try inserting `NULL` primary key. Error [ ]
    - [x] Create a new table which is related to your existing table with a foreign key
    - [x] Try inserting different values for foreign key to produce different errors
        - Try inserting none existing foreign key. Error [ ]
        - Try inserting duplicate foreign key. Error [ ]
        - Try inserting `NULL` foreign key. Error [ ]
- [x] Perceive different types of joins
    - [x] Write the corresponding set operation for each join like the given example
        - A Inner Join B : A ∩ B
        - A Left Outer Join B : `[FILL HERE]`
        - A Right Outer Join B : `[FILL HERE]`
        - A Full Outer Join B : `[FILL HERE]`
    - [x] Test different joins on you tables
- [x] Work with functions
    - [x] Write a query for each present function in the document
     
## [Phase 7](https://star-academy.github.io/codestar-documents/docs/software-engineering/phase08-EFCore)

- [x] Implement Top 3 Student project with EfCore in C#

## Web history

- [x] Before starting: Read the link about history and purpose of creating & developing Web, then answer this questions:
  - [x] How did developers provide server-client softwares for users before creation of web technologies?
  
      با استفاده از برنامه های تحت دسکتاپ

  - [x] What was the main trouble with traditional technologies before web?
  
      مشکل در آپدیت، تفاوت در نسخه های موحود در هر کامپیوتر

  - [x] How did web overcome this main trouble?
  
     هر کاربر می تواند با داشتن تنها یک مرورگر به نسخه ی واحدی از وب اپلیکیشن دسترسی پیدا کند

## ASP.NET Core

- [x] Getting Started with HTTP:
  - [x] What does a protocol mean?
  
    قراردادی مشخص برای انتقال دیتا

  - [x] Why designing a protocol for communication is important prerequirement of all other web related technologies?
  
    چون برای ارتباط بین کلاینت و سرور نیاز به قرادادی مشخض داریم

  - [x] Try to get familier with HTTP by reading links.
  - [x] Why HTTP is most popular protocol in web technologies?

    این پروتکل روش دریافت و ویرایش منابعی را مشخص می‌کند که لزوما صفحات وب نیستند و به همین علت می‌توان آن را در جاهای مختلفی استفاده کرد.

  - [x] What is the most interesting aspect of HTTP in your opinion?
     توسعه پذیری آن و استفاده شدن در مکان‌های مختلف
    
- [x] Getting Started with REST:
  - [x] Read mentioned links.
  - [x] Why do we need RESTful APIs?
  
   اکثر چیزهایی که در دنیای وب با آن‌ها تعامل می‌کنیم را می‌توان به صورت یک منبع که اعمال CRUD بر روی آن‌ها انجام می‌شود، مدل کرد و به همین خاطر API های REST برای کار با اکثر مفاهیم مفید هستند.

- [x] Getting Started with Asp.net Core:
  - [x] Read mentioned links.
  - [x] Create a hello world API.
  - [x] Call your api from browser.
  - [x] Play with routing options! (Try to use it & enjoy it!)
  - [x] Why do we need configurable routings in web development?
  
    با توجه به اینکه ممکن است نیاز باشد مسیر کار کردن با یک منبع را با توجه به نیاز تغییر دهیم، به مسیرهای قابل ویرایش نیاز داریم.
  
  - [x] Play with dependency injection! (Define an interface & inject interface implementation to code)
  - [x] Why do we need dependency injection?
  
    با توجه به اصول سالید و نیاز به تغییر جهت وابستگی‌ها، و توسعه‌پذیر کردن کد، برای تغییر رفتار در یک کد از پیش نوشته شده، وابستگی‌های مورد نیاز را اینجکت می‌کنیم.
  - [x] Play with parameter binding! (use different modes)
  - [x] Install postman.
  - [x] Call your APIs with postman.
  
- [x] Implement Asp.net Core Project:
  - [x] Design your search API.
  - [x] Implement & Test your API.
